// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicationParse;

#nullable disable

namespace PublicationParse.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240430140133_MigIntPassword")]
    partial class MigIntPassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PublicationParse.AE_2098001_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALAN_BILGISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANAHTAR_KELIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ATIF_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("CILT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DERGI_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENDEKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENDEKS_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERISIM_LINKI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERISIM_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERISIM_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAKEM_TUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAKEM_TUR_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILK_SAYFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAKALE_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAKALE_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAKALE_TURU_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_SAYI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_SAYI_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAYI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEHIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SON_SAYFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPONSOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Makale");
                });

            modelBuilder.Entity("PublicationParse.AE_2098001_Entity_Rebuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALAN_BILGISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANAHTAR_KELIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ATIF_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("CILT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DERGI_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENDEKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENDEKS_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERISIM_LINKI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERISIM_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERISIM_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAKEM_TUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAKEM_TUR_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILK_SAYFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAKALE_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAKALE_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAKALE_TURU_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_SAYI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_SAYI_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAYI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEHIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SON_SAYFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPONSOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MakaleRebuild");
                });

            modelBuilder.Entity("PublicationParse.AE_2098002_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALAN_BILGISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANAHTAR_KELIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ATIF_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("BASIM_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASIM_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOLUM_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOLUM_ILK_SAYFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BOLUM_SON_SAYFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDITOR_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERISIM_LINKI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KACINCI_BASIM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KATKI_DUZEYI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KATKI_DUZEYI_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KITAP_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KITAP_TUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KITAP_TUR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAYFA_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEHIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_EVI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("PublicationParse.AE_2098003_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALAN_BILGISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANAHTAR_KELIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("ENDEKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENDEKS_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAKEMLIK_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAKEMLIK_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAKEMLIK_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEHIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_YERI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hakemlik");
                });

            modelBuilder.Entity("PublicationParse.AE_2098004_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ALAN_INDEKS_ATF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("BESTECI_ESER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIGER_ATIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DONEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESCI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESER_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GZLSNTULSL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCAL_ATIF_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSCI_INDEKS_ATF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUR_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULUSAL_KIT_ATF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULUSLAR_KIT_ATF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Atıflar");
                });

            modelBuilder.Entity("PublicationParse.AE_2098005_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALAN_BILGISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANAHTAR_KELIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ATIF_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("BASIM_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASIM_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASIM_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BILDIRI_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BILDIRI_SUNUM_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BILDIRI_SUNUM_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BILDIRI_TUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BILDIRI_TUR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CILT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERISIM_LINKI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETKINLIK_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETKINLIK_BAS_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETKINLIK_BIT_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILK_SAYFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_SAYI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZEL_SAYI_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRINT_ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAYI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEHIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SON_SAYFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPONSOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DILI_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DURUMU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_DURUMU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAYIN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAZAR_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bildiriler");
                });

            modelBuilder.Entity("PublicationParse.AE_2098006_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Editorlukler");
                });

            modelBuilder.Entity("PublicationParse.AE_2098008_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAAL_DETAY_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAAL_DETAY_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISYERI_TURU_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISYERI_TURU_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KISI_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURULUS_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURUM_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURUM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODUL_ACIKLAMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODUL_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODUL_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODUL_KISI_SIRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODUL_TARIH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODUL_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODUL_TUR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_KURUM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_KURUM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UNVAN_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_UNVAN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Oduller");
                });

            modelBuilder.Entity("PublicationParse.AE_2098009_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("YonetilenTezler");
                });

            modelBuilder.Entity("PublicationParse.AE_2098010_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("BAS_TAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIT_TAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUTCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURUM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURUM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARA_BIRIMI_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARA_BIRIMI_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_DURUMU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_DURUMU_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_KONUMU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_KONUMU_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_KONUSU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_TURU_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNVAN_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNVAN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("PublicationParse.AE_2098011_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKADEMIK_YIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKADEMIK_YIL_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("DERS_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DERS_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DERS_SAATI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIL_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIL_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EKLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OGRENIM_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OGRENIM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OgretimFaaliyeti");
                });

            modelBuilder.Entity("PublicationParse.AE_2098013_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SanatsalveMeslekiEtkinlikler");
                });

            modelBuilder.Entity("PublicationParse.AE_2098014_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patentler");
                });

            modelBuilder.Entity("PublicationParse.AE_2098016_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("BAS_TAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIT_TAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURULUS_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURULUS_TURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURULUS_TURU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UYELIK_DURUMU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UYELIK_DURUMU_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UYELIK_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BilimselDanismanliklarveUyelikler");
                });

            modelBuilder.Entity("PublicationParse.AE_2098017_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("BAS_TAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIT_TAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CALISMA_DURUMU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DENEYIM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GOREV_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISYERI_TUR_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISYERI_TUR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IS_TANIMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURULUS_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURULUS_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UniversiteDisiDeneyimler");
                });

            modelBuilder.Entity("PublicationParse.AE_2098021_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AKTIF_PASIF_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.Property<string>("BASTAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BITTAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUNCELLEME_TARIHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICERIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KAPSAM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KISI_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURUM_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURUM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SURE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESV_PUAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUR_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUR_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULKE_SEHIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNVAN_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNVAN_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Arastirma");
                });

            modelBuilder.Entity("PublicationParse.AE_2098022_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasarim");
                });

            modelBuilder.Entity("PublicationParse.DatabaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PublicationParse.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadroUnvan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Academicians");
                });
#pragma warning restore 612, 618
        }
    }
}
